### ISSUE TITLE
Improve ReadMe

### ISSUE THREAD

**Issue by 4e0x** [4e0x/w-bomber#2]
#### What happened?
Improve the ReadMe/Installation doc with no icons

#### Steps to Reproduce
N/A

#### RCA
N/A

#### Solution
Re-deploy ReadMe by removing junk

**Comment by 4e0x** [comment]
Will re-deploy post [broken extension](https://github.com/4e0x/w-bomber/issues/1#issue-1848658070) is fixed.
```
?
```

**Comment by nitin-pandita** [comment]
@4e0x hope you are doing well , I would like to have this issue

**Comment by 4e0x** [comment]
> @4e0x hope you are doing well , I would like to have this issue

Heyy @nitin-pandita I'm doing well. Hope the same with you.

Ummm sure, I can assign it.

**Comment by nitin-pandita** [comment]
> > @4e0x hope you are doing well , I would like to have this issue
> 
> Heyy @nitin-pandita I'm doing well. Hope the same with you.
> 
> Ummm sure, I can assign it.

@4e0x thank you

**Comment by nitin-pandita** [comment]
> > > @4e0x hope you are doing well , I would like to have this issue
> > 
> > 
> > Heyy @nitin-pandita I'm doing well. Hope the same with you.
> > Ummm sure, I can assign it.
> 
> @4e0x Thank you, I will try to solve this issue as soon as possible
